### ISSUE TITLE
Consider hosting add-ons here?

### ISSUE THREAD

**Issue by SkywardShadow** [Resike/Recount#1]
Would you consider hosting your add-ons here so those of us who wish may avoid Overwolf? Thank you!

This one and MoveAnything are at the top of my list!

Here's the conversation on another add-on:
https://github.com/SLOKnightfall/BetterWardrobe/issues/250

**Comment by tflo** [comment]
Yep. Just adding a release zip to your Release assets would be a good step. This and adding some tags (like `wow-addon`, `addon`,  `world-of-warcraft`) would – probably –  make it eligible for the Github catalogue of [instawow](https://github.com/layday/instawow) or/and [strongbox](https://github.com/ogri-la/strongbox).

Ideally you could register the repo with [WoWUp Hub](https://wowup.io/guide/wowup/hub). This requires a release zip and a `release.json`, and ~~[AFAIK](https://github.com/WowUp/WowUp/issues/1062#issuecomment-985318186) you still need~~ to register each addon individually on their Discord channel. --> Yes, still required, just verified with a  new addon of my own, and asked “why not using a catalogue?” – the answer was “currently for economy reasons”.

Just posting the addon on [Wago Addons](https://addons.wago.io) would also be a good thing. The process is really simple, it can grab your release from Github, also the ReadMe etc. The [BigWigsPackager](https://github.com/BigWigsMods/packager) can save you some work too.

> so those of us who wish may avoid Overwolf?

I don’t think anyone in their right mind uses this Overwolf stuff ;)
